package AppLib.ApiLib.payloadutils;

import AppLib.ApiLib.pojolib.programpojo;
import CoreLib.VariableUtil.GlobalVariable;
import CoreLib.stringutil.StringUtils;

public class PayloadProgramModule extends programpojo{
	
	public static String createProgramPayload() {
		
		setProgramcode(StringUtils.randomPrgCodeGenerator());
	    setProgramename(StringUtils.randomProgramNamegenerator());
	    setProgramsequence(StringUtils.randomProgramSequenceGenerator());
			
		return "{\r\n"
				+ "  \"version\": \"\",\r\n"
				+ "  \"programCode\": \"\",\r\n"
				+ "  \"programName\": \""+getProgramename()+"\",\r\n"
				+ "  \"academyLocation\": {\r\n"
				+ "    \"id\": 1\r\n"
				+ "  },\r\n"
				+ "  \"accreditationFromDate\": \"\",\r\n"
				+ "  \"accreditationProgramAccreditation\": \"\",\r\n"
				+ "  \"accreditationTillDate\": \"\",\r\n"
				+ "  \"admissionRequirements\": \"<html>\\n<head>\\n\\t<title></title>\\n</head>\\n<body data-gr-ext-installed=\\\"\\\" data-new-gr-c-s-check-loaded=\\\"14.1235.0\\\" data-new-gr-c-s-loaded=\\\"14.1235.0\\\"></body>\\n<grammarly-desktop-integration data-grammarly-shadow-root=\\\"true\\\"></grammarly-desktop-integration></html>\\n\",\r\n"
				+ "  \"bursaryInformation\": \"<html>\\n<head>\\n\\t<title></title>\\n</head>\\n<body data-gr-ext-installed=\\\"\\\" data-new-gr-c-s-check-loaded=\\\"14.1235.0\\\" data-new-gr-c-s-loaded=\\\"14.1235.0\\\"></body>\\n<grammarly-desktop-integration data-grammarly-shadow-root=\\\"true\\\"></grammarly-desktop-integration></html>\\n\",\r\n"
				+ "  \"customData\": [],\r\n"
				+ "  \"departmentByProgramDepartmentId\": {\r\n"
				+ "    \"id\": 16,\r\n"
				+ "    \"value\": \"Academic Affairs\"\r\n"
				+ "  },\r\n"
				+ "  \"duration\": \"\",\r\n"
				+ "  \"educationDepartmentProgramCode\": \"\",\r\n"
				+ "  \"educationDepartmentRegistrationDate\": \"\",\r\n"
				+ "  \"fieldOfStudyLanguageTwo\": \"\",\r\n"
				+ "  \"fieldOfStudyOtherLanguage\": \"\",\r\n"
				+ "  \"graduationCertificateToBePrint\": \"\",\r\n"
				+ "  \"isHtmlContent\": true,\r\n"
				+ "  \"isLongDistanceProgram\": true,\r\n"
				+ "  \"isPeriodTransitionApplicable\": false,\r\n"
				+ "  \"isSingleCourseProgram\": true,\r\n"
				+ "  \"presentationLanguageId\": \"\",\r\n"
				+ "  \"programAreaOfInterests\": [],\r\n"
				+ "  \"programCategory\": {\r\n"
				+ "    \"id\": 7,\r\n"
				+ "    \"value\": \"BTech\"\r\n"
				+ "  },\r\n"
				+ "  \"programCourseGroupMapping\": [],\r\n"
				+ "  \"programDesignator\": \"\",\r\n"
				+ "  \"programDocuments\": [],\r\n"
				+ "  \"programGroup\": {\r\n"
				+ "    \"id\": 1,\r\n"
				+ "    \"value\": \"Under Graduate\"\r\n"
				+ "  },\r\n"
				+ "  \"programMarkGrade\": \"G\",\r\n"
				+ "  \"programNameLanguageOne\": \"\",\r\n"
				+ "  \"programNameLanguageThree\": \"\",\r\n"
				+ "  \"programNameLanguageTwo\": \"\",\r\n"
				+ "  \"programNameToBePrint\": \""+getProgramename()+"\",\r\n"
				+ "  \"programNameToBePrintLanguageOne\": \"\",\r\n"
				+ "  \"programNameToBePrintLanguageThree\": \"\",\r\n"
				+ "  \"programNameToBePrintLanguageTwo\": \"\",\r\n"
				+ "  \"programQualifier\": \"\",\r\n"
				+ "  \"programRegistrationId\": \"\",\r\n"
				+ "  \"programSecondQualifier\": \"\",\r\n"
				+ "  \"programSequence\": \""+getProgramsequence()+"\",\r\n"
				+ "  \"programShortName\": \"Btech computer science\",\r\n"
				+ "  \"programShortNameLanguageOne\": \"\",\r\n"
				+ "  \"programShortNameLanguageThree\": \"\",\r\n"
				+ "  \"programShortNameLanguageTwo\": \"\",\r\n"
				+ "  \"programSubMerchantId\": \"\",\r\n"
				+ "  \"publishInCatalogue\": false,\r\n"
				+ "  \"remark\": \"\",\r\n"
				+ "  \"saqaId\": \"\",\r\n"
				+ "  \"selectionCriteria\": \"<html>\\n<head>\\n\\t<title></title>\\n</head>\\n<body data-gr-ext-installed=\\\"\\\" data-new-gr-c-s-check-loaded=\\\"14.1235.0\\\" data-new-gr-c-s-loaded=\\\"14.1235.0\\\"></body>\\n<grammarly-desktop-integration data-grammarly-shadow-root=\\\"true\\\"></grammarly-desktop-integration></html>\\n\",\r\n"
				+ "  \"status\": \"C\",\r\n"
				+ "  \"user\": {\r\n"
				+ "    \"id\": 1,\r\n"
				+ "    \"value\": \"SYSADMIN / SystXm XdmXnXstrXtXr\",\r\n"
				+ "    \"code\": null\r\n"
				+ "  },\r\n"
				+ "  \"videoURL\": \"\",\r\n"
				+ "  \"whetherAccreditation\": false,\r\n"
				+ "  \"whetherCreateNewAdmission\": true,\r\n"
				+ "  \"whetherSucceedingProgram\": false\r\n"
				+ "}";		
	}
	
	
public static String createProgramBatchPayload() {
	   
	   setBatchname(StringUtils.randomBatchGenerator());
	
		
		return "{\r\n"
				+ "  \"name\": \"\",\r\n"
				+ "  \"seatCapacity\": \"100\",\r\n"
				+ "  \"startDate\": \"2025-05-14\",\r\n"
				+ "  \"tillDate\": \"2026-05-22\",\r\n"
				+ "  \"maxPeriod\": \"3\",\r\n"
				+ "  \"additionalRequirementDetails\": \"\",\r\n"
				+ "  \"ageVerificationDate\": null,\r\n"
				+ "  \"allowMultipleLastPeriods\": false,\r\n"
				+ "  \"batchOfSucceedingProgram\": \"\",\r\n"
				+ "  \"batchPartTime\": false,\r\n"
				+ "  \"batchResultStatus\": [],\r\n"
				+ "  \"batchSubHoldCategory\": [],\r\n"
				+ "  \"calendar\": {\r\n"
				+ "    \"id\": 114,\r\n"
				+ "    \"value\": \"demo calendar\"\r\n"
				+ "  },\r\n"
				+ "  \"cgpaRequired\": \"0\",\r\n"
				+ "  \"completionTime\": \"\",\r\n"
				+ "  \"customData\": [],\r\n"
				+ "  \"documents\": [],\r\n"
				+ "  \"eligibilityCriteria\": \"\",\r\n"
				+ "  \"enquiryEnable\": true,\r\n"
				+ "  \"estimatedFees\": \"\",\r\n"
				+ "  \"faq\": \"\",\r\n"
				+ "  \"hasAdditionalRequirement\": false,\r\n"
				+ "  \"intakeYear\": {\r\n"
				+ "    \"id\": 15\r\n"
				+ "  },\r\n"
				+ "  \"isAdvanceConfig\": false,\r\n"
				+ "  \"isEquivalenceCheck\": false,\r\n"
				+ "  \"isFeeApplicable\": false,\r\n"
				+ "  \"isIncludeRepeatedCoursesInCGPA\": false,\r\n"
				+ "  \"isRetentionApplicable\": false,\r\n"
				+ "  \"isTransferCreditFromStudentPortalId\": false,\r\n"
				+ "  \"maxCompulsoryCourses\": \"1\",\r\n"
				+ "  \"maxOptionalCourses\": \"1\",\r\n"
				+ "  \"maxProgramCourses\": \"1\",\r\n"
				+ "  \"maxProgramCredits\": \"1000\",\r\n"
				+ "  \"minCompulsoryCourses\": \"1\",\r\n"
				+ "  \"minOptionalCourses\": \"1\",\r\n"
				+ "  \"minPeriod\": \"1\",\r\n"
				+ "  \"minProgramCourses\": \"1\",\r\n"
				+ "  \"minProgramCredits\": \"0\",\r\n"
				+ "  \"minimumCPA\": \"\",\r\n"
				+ "  \"placementProcessRequired\": \"true\",\r\n"
				+ "  \"printName\": \""+getBatchname()+"\",\r\n"
				+ "  \"programBatchPrefix\": \"\",\r\n"
				+ "  \"programBatchSeq\": \"1\",\r\n"
				+ "  \"programId\": \""+getProgramidreceived()+"\",\r\n"
				+ "  \"programMaxAge\": 0,\r\n"
				+ "  \"programMinAge\": 0,\r\n"
				+ "  \"programPeriodType\": {\r\n"
				+ "    \"id\": 1,\r\n"
				+ "    \"value\": \"Yearly\"\r\n"
				+ "  },\r\n"
				+ "  \"publishInCatalogue\": false,\r\n"
				+ "  \"retainBatch\": \"\",\r\n"
				+ "  \"roundingCount\": \"2\",\r\n"
				+ "  \"roundingMode\": \"HALF_UP\",\r\n"
				+ "  \"sgpaCgpaCalculationRule\": \"GENERIC_RULE\",\r\n"
				+ "  \"specializationPossible\": true,\r\n"
				+ "  \"version\": \"\"\r\n"
				+ "}";		
	}


	public static String CreateCoursePayload() {
		
		setCoursecode(StringUtils.randomCourseCodeGenerator());
	    setCoursename(StringUtils.randomCourseNamegenerator());
		
		return "{\n"
				+ "    \"courseCode\": \""+getCoursecode()+"\",\n"
				+ "    \"courseCodeName\": \"\",\n"
				+ "    \"courseName\": \""+getCoursename()+"\",\n"
				+ "    \"courseShortName\": \""+getCoursename()+"\",\n"
				+ "    \"nameToBePrinted\": \""+getCoursename()+"\",\n"
				+ "    \"department\": {\n"
				+ "        \"id\": 37,\n"
				+ "        \"value\": 37\n"
				+ "    },\n"
				+ "    \"assignSectionType\": \"CourseSection\",\n"
				+ "    \"hasCourseComponents\": 0,\n"
				+ "    \"whetherEvaluationExternal\": false,\n"
				+ "    \"courseMarksGrades\": \"G\",\n"
				+ "    \"courseCutOff\": \"D\",\n"
				+ "    \"whetherFixed\": \"\",\n"
				+ "    \"courseMaxMark\": \"A\",\n"
				+ "    \"courseCredits\": \"4\",\n"
				+ "    \"deficiencyStatus\": false,\n"
				+ "    \"courseDeficits\": \"R\",\n"
				+ "    \"courseDeficitsPoint\": 0,\n"
				+ "    \"courseShortDescription\": \"NA\",\n"
				+ "    \"courseRankConsidered\": \"Y\",\n"
				+ "    \"courseEntryCriteriaQuery\": \"\",\n"
				+ "    \"courseExitCriteriaQuery\": \"\",\n"
				+ "    \"whetherRepeatable\": false,\n"
				+ "    \"selectionStage\": \"COURSE_EXECUTION\",\n"
				+ "    \"version\": \"\",\n"
				+ "    \"whetherCourseExemption\": 0,\n"
				+ "    \"sectionAtComponentLevel\": false,\n"
				+ "    \"courseGradeType\": \"D2L Grade\",\n"
				+ "    \"customData\": [],\n"
				+ "    \"whetherDeleted\": \"\",\n"
				+ "    \"createdOn\": \"\",\n"
				+ "    \"includeinPromotion\": 1,\n"
				+ "    \"whetherMultipleParam\": \"\",\n"
				+ "    \"calculationRule\": null,\n"
				+ "    \"courseId\": \"\",\n"
				+ "    \"courseCodeToBePrinted\": \""+getCoursecode()+"\",\n"
				+ "    \"courseNameLanguageOne\": \"\",\n"
				+ "    \"courseShortNameLanguageOne\": \"\",\n"
				+ "    \"courseNameLanguageTwo\": \"\",\n"
				+ "    \"courseShortNameLanguageTwo\": \"\",\n"
				+ "    \"courseNameLanguageThree\": \"\",\n"
				+ "    \"courseShortNameLanguageThree\": \"\",\n"
				+ "    \"isLMSCourses\": false,\n"
				+ "    \"lMSCourseOfferYear\": \"\",\n"
				+ "    \"isPublishToLMS\": false,\n"
				+ "    \"nameToBePrintedLanguageOne\": \"\",\n"
				+ "    \"nameToBePrintedLanguageTwo\": \"\",\n"
				+ "    \"nameToBePrintedLanguageThree\": \"\",\n"
				+ "    \"isFeeApplicable\": false,\n"
				+ "    \"modulePrerequisite\": \"<html>\\n<head>\\n\\t<title></title>\\n</head>\\n<body data-gr-ext-installed=\\\"\\\" data-new-gr-c-s-check-loaded=\\\"14.1235.0\\\" data-new-gr-c-s-loaded=\\\"14.1235.0\\\"></body>\\n<grammarly-desktop-integration data-grammarly-shadow-root=\\\"true\\\"></grammarly-desktop-integration></html>\\n\",\n"
				+ "    \"isPublishInCatalogue\": false,\n"
				+ "    \"isModulePrerequisites\": false,\n"
				+ "    \"courseSequence\": \"\",\n"
				+ "    \"courseShortDescriptionInOtherLanguage\": \"\",\n"
				+ "    \"subjectAdditionalCode\": \"\",\n"
				+ "    \"hybridModule\": false,\n"
				+ "    \"moduleHEQSFLevel\": \"\",\n"
				+ "    \"ectsCredits\": 0,\n"
				+ "    \"eligibleTransferCredit\": false,\n"
				+ "    \"courseDepartments\": [\n"
				+ "        {\n"
				+ "            \"department\": {\n"
				+ "                \"id\": 37,\n"
				+ "                \"value\": 37\n"
				+ "            },\n"
				+ "            \"weightage\": \"100\"\n"
				+ "        }\n"
				+ "    ],\n"
				+ "    \"courseMultipleLanguages\": [],\n"
				+ "    \"documents\": []\n"
				+ "}";
	}


public static String createSeatPayload() {
	return "{\r\n"
			+ "  \"batchId\": "+getBatchidreceived()+",\r\n"
			+ "  \"seatType\": {\r\n"
			+ "    \"id\": 21,\r\n"
			+ "    \"value\": \"General Seat\"\r\n"
			+ "  },\r\n"
			+ "  \"seatCapacity\": \"50\",\r\n"
			+ "  \"version\": \"\",\r\n"
			+ "  \"seatsFilled\": 0,\r\n"
			+ "  \"retainSeatConfig\": null,\r\n"
			+ "  \"succeedingSeatConfig\": null,\r\n"
			+ "  \"whetherEnableEnquiry\": true\r\n"
			+ "}";
}


public static String createPeriodPayload() {
	
	setPeriodname(StringUtils.randomPeriodNamegenerator());
	return "{\r\n"
			+ "  \"programPeriodSeq\": \"1\",\r\n"
			+ "  \"programPeriodName\": \""+getPeriodname()+"\",\r\n"
			+ "  \"programPeriodStart\": \"2025-05-14\",\r\n"
			+ "  \"programPeriodEnd\": \"2026-05-22\",\r\n"
			+ "  \"printName\": \""+getPeriodname()+"\",\r\n"
			+ "  \"academicTerm\": {\r\n"
			+ "    \"id\": 66\r\n"
			+ "  },\r\n"
			+ "  \"batchId\": "+getBatchidreceived()+",\r\n"
			+ "  \"campus\": \"\",\r\n"
			+ "  \"computerUserAreaId\": \"\",\r\n"
			+ "  \"computerUserAreaValue\": \"\",\r\n"
			+ "  \"considerOnlyPromotionalCourses\": false,\r\n"
			+ "  \"customData\": [\r\n"
			+ "    {\r\n"
			+ "      \"cf1\": \"\",\r\n"
			+ "      \"id\": \"\",\r\n"
			+ "      \"version\": \"\"\r\n"
			+ "    }\r\n"
			+ "  ],\r\n"
			+ "  \"enrollmentLastDate\": \"2025-05-24\",\r\n"
			+ "  \"examCancellationApplicableFromDate\": \"\",\r\n"
			+ "  \"examCancellationApplicableTillDate\": \"\",\r\n"
			+ "  \"id\": \"\",\r\n"
			+ "  \"isCurrentPeriodOfProgram\": \"\",\r\n"
			+ "  \"isLastPeriodOfProgram\": true,\r\n"
			+ "  \"isPromotionParamCourseType\": true,\r\n"
			+ "  \"isStudentJourneyPeriodSequesnce\": false,\r\n"
			+ "  \"kysStartDate\": \"\",\r\n"
			+ "  \"kysEndDate\": \"\",\r\n"
			+ "  \"maxCourses\": \"1\",\r\n"
			+ "  \"maxCredit\": \"1000\",\r\n"
			+ "  \"minCourses\": \"1\",\r\n"
			+ "  \"minCredits\": \"0\",\r\n"
			+ "  \"minResidenceCredits\": \"\",\r\n"
			+ "  \"minimumCGPAForPromotion\": \"\",\r\n"
			+ "  \"minimumCreditsForPromotion\": \"\",\r\n"
			+ "  \"minimumSGPAForPromotion\": \"\",\r\n"
			+ "  \"offeredAtALId\": \"\",\r\n"
			+ "  \"offeredAtALName\": \"\",\r\n"
			+ "  \"progBatchPeriodPromotionCriteriaDetails\": [\r\n"
			+ "    {\r\n"
			+ "      \"period\": {\r\n"
			+ "        \"id\": \"\"\r\n"
			+ "      },\r\n"
			+ "      \"sequence\": 1,\r\n"
			+ "      \"isCourses\": true,\r\n"
			+ "      \"promotionCriteriaRules\": []\r\n"
			+ "    }\r\n"
			+ "  ],\r\n"
			+ "  \"programBatchCampusDetails\": [],\r\n"
			+ "  \"programBatchPeriodStatusDetails\": [],\r\n"
			+ "  \"programPeriodAutoPromotion\": \"N\",\r\n"
			+ "  \"programPeriodEndDate\": \"\",\r\n"
			+ "  \"programPeriodExternalPromotion\": \"N\",\r\n"
			+ "  \"programPeriodRankBasis\": \"GRADE_BASED\",\r\n"
			+ "  \"programPeriodStartDate\": \"\",\r\n"
			+ "  \"registrationProcessReq\": false,\r\n"
			+ "  \"registrationSetupName\": \"\",\r\n"
			+ "  \"registrationTermSetupDetailId\": \"\",\r\n"
			+ "  \"specializationReq\": false,\r\n"
			+ "  \"studentCourseSelectionStartDate\": \"\",\r\n"
			+ "  \"studentCourseSelectionEndDate\": \"\",\r\n"
			+ "  \"version\": \"\",\r\n"
			+ "  \"whetherPlacementPeriod\": false\r\n"
			+ "}";
}

public static String payloadCourseMapping() {
	return "{\r\n"
			+ "  \"version\": \"\",\r\n"
			+ "  \"courseId\": \"\",\r\n"
			+ "  \"batchId\": "+getBatchidreceived()+",\r\n"
			+ "  \"whetherOptional\": false,\r\n"
			+ "  \"courseCode\": \"\",\r\n"
			+ "  \"courseName\": \"\",\r\n"
			+ "  \"courseGroupCount\": \"\",\r\n"
			+ "  \"courseGroupId\": \"\",\r\n"
			+ "  \"courseGroupName\": \"\",\r\n"
			+ "  \"courseIds\": \""+getCourseIdrecived()+"\",\r\n"
			+ "  \"courseRepeatable\": \"\",\r\n"
			+ "  \"enrollmentCriteria\": \"\",\r\n"
			+ "  \"id\": \"\",\r\n"
			+ "  \"isOfferedYearly\": false,\r\n"
			+ "  \"periodDisplayObj\": null,\r\n"
			+ "  \"periodId\": \"\",\r\n"
			+ "  \"periodObj\": null,\r\n"
			+ "  \"whetherMajor\": false\r\n"
			+ "}"
;}


public static String payloadCourseMappingwithPeriod() {
	return "[\r\n"
			+ "  {\r\n"
			+ "    \"id\": "+getBatchcourseidreceived()+",\r\n"
			+ "    \"version\": 0,\r\n"
			+ "    \"courseId\": "+getCourseIdrecived()+",\r\n"
			+ "    \"batchId\": "+getBatchidreceived()+",\r\n"
			+ "    \"whetherOptional\": false\r\n"
			+ "  }\r\n"
			+ "]";
}


}
